### PR TITLE
Big bunch of fixes

### PR DESCRIPTION
**Pull request by iorlas**
W/o this fix, lifebloom ignores heal bonus and always ticks like w/o player gear.
So, i can write sql update file, but i think it'll be easier for you just to put it in next sql update bunch :)

### CODE REVIEW

**Comment by iorlas** [comment]
By the way, how to ignore other commits and to say Github "i have really cloned to upstream repo!" ?
I imagine it will be next month, after over 20 merges +_+

**Comment by iorlas** [comment]
And Swiftmend spell(id 18562). It needs to remove Regrowth or Rejuvenation spell on Swiftmend spellcast.

**Comment by iorlas** [comment]
And to Swiftmed fix. As i see, in mangos/mangos you're using different function. So, i think it'll be better.
https://github.com/mangos/mangos/blob/master/src/game/SpellEffects.cpp#L3747

**Comment by iorlas** [comment]
Mangle now works like it needed. All bleeding effects now works with it.
In before, mangle logic was placed in Unit::SpellDamageBonusTaken, but bleeding effects will never be a "spell damage". So, we can just move logic to Unit::MeleeDamageBonusTaken with merging existing code(shred, i mean).
I tried to find some code for Mangle bleed effects in mangos/mangos, but "grep -R" gives only not interesting codelines.
Perhaps, mangos/mangos has same problem and this fix can be ported into latest repo.

**Comment by VladimirMangos** [comment]
all cases reviewed

**Pull request closed without merging**
